# -*- coding: utf-8 -*-
"""Training_day_9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S20l1ek2w02C8l7LIOVokcDp0xxQMqbK
"""

Hackerrank problem : Tree:Level Order Traversal

class Node:
    def levelOrder(root):
        q=[]
        q.append(root)
        while q:
            ele=q.pop(0)
            print(ele,end=" ")
            if ele.left:
                q.append(ele.left)
            if ele.right:
                q.append(ele.right)

Hackerrank problem : Tree:Hieght of a binary tree

class Node:
    def height(root):
        if root is None:
            return -1
        return 1+max(height(root.left),height(root.right))

Hackerrank problem : BST-Lowest Common Ancestor

class Node:
    def lca(root, v1, v2):
        if root.info>v1 and root.info>v2:
            return lca(root.left,v1,v2)
        elif root.info<v1 and root.info<v2:
            return lca(root.right,v1,v2)
        else:
            return root
    tree = BinarySearchTree()

Hackerrank problem : Is this a BST

class Node:
def check_binary_search_tree_(root):
    res = []

    def inorder(root):
        if root is None:
            return
        inorder(root.left)
        res.append(root.data)
        inorder(root.right)

    inorder(root)

    for i in range(len(res) - 1):
        if res[i] >= res[i + 1]:
            return False

    return True

leet 100,112,111,222,226,247