# -*- coding: utf-8 -*-
"""Training_day_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PGEOa6OkLnm5Y4rs9I-7Sr8d0fXeVD3-
"""

l=list(map(int,input().split()))        // left rotation by k no.of times
k=int(input("enter the no.of rotation :"))
for i in range(k):
    temp=l[0]
    for i in range(1,len(l)):
        l[i-1]=l[i]
    l[-1]=temp
print(l)

problem no:189
                                        //right rotation
r=k%len(nums)
for i in range(len(nums)//2):
    temp=nums[i]
    nums[i]=nums[len(nums)-i-1]
    nums[len(nums)-i-1]=temp
for i in range(r//2):
    temp=nums[i]
    nums[i]=nums[r-i-1]
    nums[r-i-1]=temp
for i in range((len(nums)-r)//2):
    temp=nums[i+r]
    nums[i+r]=nums[len(nums)-i-1]
    nums[len(nums)-i-1]=temp

l1=[1,3,5]              //two pointer problems
l2=[2,4,6,7,8,9]
l3=[]
i=0
j=0
while i < len(l1) and j < len(l2):
    if l1[i]<l2[j]:
        l3.append(l1[i])
        i+=1
    else:
        l3.append(l2[j])
        j+=1
while i < len(l1):
    l3.append(l1[i])
    i+=1
while j < len(l2):
    l3.append(l2[j])
    j+=1
print(l3)

problem no : 125

class Solution:
    def isPalindrome(self, s: str) -> bool:
        left, right = 0, len(s) - 1

        while left < right:
            while left < right and not s[left].isalnum():
                left += 1

            while left < right and not s[right].isalnum():
                right -= 1

            if s[left].lower() != s[right].lower():
                return False

            left += 1
            right -= 1

        return True

problem no:680

class Solution:
    def validPalindrome(self, s: str) -> bool:
        i,j = 0, len(s) - 1
        while i < j:
            if s[i]!=s[j]:
                skip_left=s[i+1:j+1]
                skip_right=s[i:j]
                if skip_left==skip_left[::-1] or skip_right==skip_right[::-1]:
                    return True
                else:
                    return False
            i+=1
            j-=1
        return True

books=[2,1,3,1,3,4,2,1,3,4,6,7,8,9,9,9]      //sliding window static problem
k=3
n=len(books)
s=sum(books[:k])
m=s
for i in range(1,n-k+1):
    s=s-books[i-1]+books[i+k-1]
    m=max(m,s)
print(m)

problem no:643

class Solution:
    def findMaxAverage(self, nums: List[int], k: int) -> float:
        n=len(nums)
        s=sum(nums[:k])
        m=s
        for i in range(1,n-k+1):
            s=s-nums[i-1]+nums[i+k-1]
            m=max(m,s)
        return m/k

subarray
--------

> you cant skip . it should be in an order
> all subarray problems are related to sliding window problems

subsequence
-----------

> you can skip
> it is recursion

problem no:263

class Solution:
    def isUgly(self, n: int) -> bool:
        if n<=0:
            return False
        for i in [2,3,5]:
            while n%i==0:
                n=n//i
        return n==1