# -*- coding: utf-8 -*-
"""training_day_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wdBPwNFT6kYPlW35mBdo1aJDVdzSat0
"""

problem no:66

class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        for i in range(len(digits)-1,-1,-1):
            if digits[i]==9:
                digits[i]=0
            else:
                digits[i]=digits[i]+1
                return digits
        return [1]+digits

problem no:136

class Solution:
    def singleNumber(self, nums: List[int]) -> int:
        for i in nums:
            if nums.count(i)==1:
                return i

problem no:

class Solution:
    def lemonadeChange(self, bills: List[int]) -> bool:
        five,ten=0,0
        for coin in bills:
            if coin==5:
                five+=1
            elif coin==10:
                if five>0:
                    five-=1
                    ten+=1
                else:
                    return False
            else:
                if five>0 and ten>0:
                    five-=1
                    ten-=1
                elif five>=3:
                    five-=3
                else:
                    return False
        return True

problem no:268

class Solution:
    def missingNumber(self, nums: List[int]) -> int:

        exct=sum(nums)
        n=len(nums)
        h=0
        h=n*(n+1)//2
        return h-exct

problem no:231

class Solution:
    def isPowerOfTwo(self, n: int) -> bool:
        if n<1:
            return False
        if n&(n-1)==0:
            return True
        else:
            return False

l=[2,3,4,3,3,5,4]
m,c=0,0
for i in l:
    if i>m:
        m=i
        c+=1
print(c)

problem no:55

class Solution:
    def canJump(self, nums: List[int]) -> bool:
        petrol=0
        for p in nums:
            if petrol<0:
                return False
            elif p>petrol:
                petrol=p
            petrol-=1
        return True

l=[2,3,3,4,5,6]  //second largest element in a list
for i in l:
    if i>max:
        max2=max1
        max=i
    elif i>max2 and i!=max:
        max2=i
print(max2)

l=[1,3,1,3,1,2,1,4,2,2,2,2,2]  //frequently occured largest element and second largest element
d={}
for i in l:
    if i not in d:
        d[i]=1
    else:
        d[i]+=1
ele,max=0,0
for i in d:
    if d[i]>max:
        max=d[i]
        ele=i
print(ele)

n=int(input("enter the population"))
vote=list(map(int,input().split()))
age=list(map(int,input().split()))
c=[0]*(max(vote))
for i in range(n):
    if age[i]>=18:
        c[vote[i]-1]+=1
m=max(c)
print(c.index(m)+1)

l=list(map(int,input().split()))  //left rotating a list 2 times
temp1=l[0]
temp2=l[1]
for i in range(len(l)-2):
    l[i]=l[i+2]
l[len(l)-2]=temp1
l[len(l)-1]=temp2
print(*l)

l=list(map(int,input().split()))  //left rotating a list 1 time
temp1=l[0]
for i in range(len(l)-1):
    l[i]=l[i+1]
l[len(l)-1]=temp1
print(*l)

