# -*- coding: utf-8 -*-
"""Training_day_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrtGXSbmVjqB61VBLn8lE0ACvuEjz6Gf
"""

problem no:79

class Solution:
    def exist(self, board: List[List[str]], word: str) -> bool:

        def possible(board, i, j, k):
            if k == len(word):
                return True

            if (i < 0 or i >= len(board) or
                j < 0 or j >= len(board[0]) or
                board[i][j] != word[k]):
                return False

            temp = board[i][j]
            board[i][j] = "#"

            found = (
                possible(board, i-1, j, k+1) or
                possible(board, i+1, j, k+1) or
                possible(board, i, j-1, k+1) or
                possible(board, i, j+1, k+1)
            )

            board[i][j] = temp
            return found

        for i in range(len(board)):
            for j in range(len(board[0])):
                if possible(board, i, j, 0):
                    return True

        return False

problem no:20                   //starting of stack problem

class Solution:
    def isValid(self, s: str) -> bool:
        stack=[]
        for c in s:
            if c=='{':
                stack.append('}')
            elif c=='[':
                 stack.append(']')
            elif c=='(':
                 stack.append(')')
            elif len(stack)==0 or stack.pop()!=c:
                return False
        return len(stack)==0

problem no:844

class Solution:
    def backspaceCompare(self, s: str, t: str) -> bool:
        def process(text):
            stack = []

            for ch in text:
                if ch == '#':
                    if stack:
                        stack.pop()
                else:
                    stack.append(ch)

            return "".join(stack)

        return process(s) == process(t)

problem no : 71

class Solution:
    def simplifyPath(self, path: str) -> str:
        stack = []

        for part in path.split('/'):
            if part == '' or part == '.':
                continue
            elif part == '..':
                if stack:
                    stack.pop()
            else:
                stack.append(part)

        return '/' + '/'.join(stack)

problem no:1700

class Solution:
    def countStudents(self, students: List[int], sandwiches: List[int]) -> int:
        n=len(students)
        while students and sandwiches and sandwiches[0] in students:
            if students[0]!=sandwiches[0]:
                students.append(students.pop(0))
            else:
                n-=1
                students.pop(0)
                sandwiches.pop(0)
        return n

problem no:1544

class Solution:
    def makeGood(self, s: str) -> str:
        stack = []

        for ch in s:
            if stack and abs(ord(ch) - ord(stack[-1])) == 32:
                stack.pop()
            else:
                stack.append(ch)

        return "".join(stack)

problem no:496                      //monotonic stack

class Solution:
    def nextGreaterElement(self, nums1: List[int], nums2: List[int]) -> List[int]:
        d={}
        stack=[]
        for curr in nums2:
            while stack and stack[-1]<curr:
                ele=stack.pop()
                d[ele]=curr
            stack.append(curr)
        while stack:
            d[stack.pop()]=-1
        res=[]
        for i in nums1:
            res.append(d[i])
        return res

problem no:739

class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        n = len(temperatures)
        res = [0] * n
        stack = []

        for i in range(n - 1, -1, -1):
            while stack and temperatures[i] >= temperatures[stack[-1]]:
                stack.pop()

            if stack:
                res[i] = stack[-1] - i

            stack.append(i)

        return res