# -*- coding: utf-8 -*-
"""Training June 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nNqUCfn84o5bd96flryburC3o9L_Ydwg
"""

a=float(input("enter the num:"))
print(a+a)

a,b=map(int,input("enter the nums: ").split())
print(a,b)

a=5
b=7
print(~-20)
print(~a)

w=int(input())
if(w%2!=0 or w==2):
    print("NO")
else:
    print("yes")

x=int(input())
if x<5:
    print(1)
elif x%5==0:
    print(x//5)
else:
    print(x//5+1)

a=int(input("enter the wieght of limak"))
b=int(input("enter the wieght of Bob"))
count=0
while(a<=b):
    a=a*3
    b=b*2
    count+=1
print(count)

n=int(input("enter the total no.of travel"))
m=int(input("enter the total no.of days using metro card"))
a=int(input("cost of normal ticket"))
b=int(input("cost of metro card"))
if a*m<b:
    print(a*n)
else:
    print(((n//m)*b)+min(b,(n%m)*a))