# -*- coding: utf-8 -*-
"""Training_day_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uWMzrOKu4eu_kv9g0KTBvRWjRWxdzUXn
"""

if we want to find the length of a list from one point to another we use n-l+1
n=upper limit
l=lower limit

list=[2,1,6,2,1,2,4,7,8,1,2] //find the largest subarray that has the sum <=10
k=10
r,l,s,m=0,0,0,0
while r<len(list):
    s+=list[r]
    while s>k:
        s-=list[l]
        l+=1
    length=r-l+1
    m=max(m,length)
    r+=1
print(m)

problem no:713

class Solution:
    def numSubarrayProductLessThanK(self, nums: List[int], k: int) -> int:
        if k<=1:
            return 0
        l,r=0,0
        cnt,product=0,1
        while(r<len(nums)):
            product*=nums[r]
            while product>=k:
                product//=nums[l]
                l=l+1
            cnt+=r-l+1
            r+=1
        return cnt

problem no:1423

class Solution:
    def maxScore(self, cardPoints: List[int], k: int) -> int:
        n=len(cardPoints)
        s=sum(cardPoints[:k])
        m=s
        for i in range(k):
            s=s-cardPoints[k-1-i]+cardPoints[n-1-i]
            m=max(m,s)
        return m

password = input("Enter the password: ")
special = "!@#$%^&*()-_=+[]{}\\|;:'\",.<>/?`~"   //password validity

has_lower = False
has_upper = False
has_digit = False
has_special = False

if len(password) >= 8:
    for ch in password:
        if ch.islower():
            has_lower = True
        if ch.isupper():
            has_upper = True
        if ch.isdigit():
            has_digit = True
        if ch in special:
            has_special = True

    if has_lower and has_upper and has_digit and has_special:
        print("valid password")
    else:
        print("invalid Password")
else:
    print("invalid Password")

binary search problems

l=[2,1,2,1,3,4,7,1,2,3,5,3]         //linear search
k=6
for i in l:
    if i==k:
        print("YES")
        break
else:
    print("no")

problem no:704 //binary search

class Solution:
    def search(self, nums: List[int], target: int) -> int:
        l,r=0,len(nums)-1
        while l<=r:
            mid=(l+r)//2
            if nums[mid]==target:
                return mid
            elif nums[mid]<target:
                l=mid+1
            else:
                r=mid-1
        return -1

problem no:35


class Solution:
    def searchInsert(self, nums: List[int], target: int) -> int:
        l, r = 0, len(nums) - 1

        while l <= r:
            mid = (l + r) // 2

            if nums[mid] == target:
                return mid
            elif nums[mid] < target:
                l = mid + 1
            else:
                r = mid - 1

        return l

problem no:34

class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
        res=[-1,-1]
        n=len(nums)
        s,e=0,n-1
        while s<=e:
            m=(s+e)//2
            if nums[m]==target:
                res[0]=m
                e=m-1
            elif nums[m]<target:
                s=m+1
            else:
                e=m-1
        s,e=0,n-1
        while s<=e:
            m=(s+e)//2
            if nums[m]==target:
                res[1]=m
                s=m+1
            elif nums[m]<target:
                s=m+1
            else:
                e=m-1

        return res

problem no:164

class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        s,e=1,len(nums)-1
        if e==0:
            return 0
        elif nums[0]>nums[1]:
            return 0
        elif nums[-1]>nums[-2]:
            return e
        while s<=e:
            mid=(s+e)//2
            if nums[mid-1]<nums[mid]>nums[mid+1]:
                return mid
            elif nums[mid] < nums[mid+1]:
                s=mid+1
            else:
                e=mid-1

problem no:74

class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
        row=len(matrix)
        col=len(matrix[0])
        s,e=0,(row*col)-1
        while s<=e:
            m=(s+e)//2
            i=m//col
            j=m%col
            if matrix[i][j]==target:
                return True
            elif matrix[i][j]<target:
                s=m+1
            else:
                e=m-1
        return False

ivide matrix ine nammal oru full list aayit aahn kaanunnath . oru linear list
so row=len(matrix) enn paranjal , list inte ullile no.of lists , ivide its 3. col=len(matrix[0]) enn paranjal oru listinte ullile no.of elements, question il ath 3 aayirunnu

athupole (row*col)-1 enn paranjal length of matrix

problem no: 875

class Solution:
    def minEatingSpeed(self, piles: List[int], h: int) -> int:
        def can_eat(n,piles,h):
            total=0
            for p in piles:
                total+=math.ceil(p/mid)
            if total>h:
                return False
            else:
                return True
        s,e=1,max(piles)
        while s<=e:
            mid=(s+e)//2
            if can_eat(mid,piles,h):
                e=mid-1
            else:
                s=mid+1
        return s

problem no:69


class Solution:
    def mySqrt(self, x: int) -> int:
        if x < 2:
            return x

        left, right = 1, x
        ans = 0

        while left <= right:
            mid = (left + right) // 2

            if mid * mid == x:
                return mid
            elif mid * mid < x:
                ans = mid
                left = mid + 1
            else:
                right = mid - 1

        return ans

problem no:2574

class Solution:
    def leftRightDifference(self, nums: List[int]) -> List[int]:
        total=sum(nums)
        left=0
        ans=[]
        for num in nums:
            total-=num
            right=total
            ans.append(abs(left-right))
            left+=num
        return ans

problem no:443

class Solution:
    def compress(self, chars: List[str]) -> int:
        i = 0
        k = 0

        while i < len(chars):
            ch = chars[i]
            count = 0

            while i < len(chars) and chars[i] == ch:
                count += 1
                i += 1

            chars[k] = ch
            k += 1

            if count > 1:
                for digit in str(count):
                    chars[k] = digit
                    k += 1

        return k