# -*- coding: utf-8 -*-
"""Training day 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foae81Cl_MJ6fyh4Q83od8fy2S7wr9U7
"""

n=int(input("enter the number"))
rev=0
while n:
    d=n%10
    rev=rev*10+d //mutiply by 10 cheynath , last place move cheyyan ahn
    n=n//10
print(rev)

num = int(input("Enter a number: "))

temp = num
sum = 0
n = len(str(num))

while temp > 0:
    digit = temp % 10
    sum += digit ** n
    temp //= 10

if sum == num:
    print(num, "is an Armstrong number")
else:
    print(num, "is not an Armstrong number")

n=int(input("enter the number"))
sum=0
s=1
rev=0
while n:
    d=n%10
    rev=d**s
    sum+=rev
    s+=1
    n=n//10
print(sum)

/*question : if 123 then 1^3+2^2+3^1 = 8 answer
             if 21234 then 2^5+1^4+2^3+3^2+4^1=answer

t=int(input())
for i in range(t):
    n=int(input())
    i=0
    k=1
    while 1:
        if i%3!=0 and i%10!=3:
            if n==k:
                print(i)
                break
            k=k+1
        i+=1

n=int(input("enter the number"))
flag=0
for i in range(2,int(n**0.5)+1):
    if(n%i==0):
        flag=1
        break
if(flag==0):
    print("prime")
else:
    print("not prime")

l=[0,1,2,3]
print(l)

l=[1,2,3,4,5,6]
l.insert(3,3.5)
print(l)

l=[1,2,3,4,5,6]
l.append(30)
print(l)

l=[1,2,3,4,5,6]
l.extend([7,8,9])
print(l)

l=[1,2,3,4,5,6]
l.append(7)
l.extend([8,9])
l.extend("ab")
l.pop()
l.append(10)
l.extend([11,12])
print(len(l))

l=[1,2,3,4,5,6]
l.pop()
print(l)

l=[1,2,3,4,5,6]
l.remove(3)
print(l)

l=[1,2,3,4,5,6]
l.clear()
print(l)

l=[1,2,3,4,5,6]
for i in l:
    l.remove(i)
print(l)

l=[5,1,2,8,4]
for i in l:
    print(i,end=" ")

l=[5,1,2,8,4]
for i in range(0,len(l)):
    print(i,end=" ")

l=[21,32,13,4,85,62,47,77]
print(l[::-1])

l=input("enter the list").split(",")
res=[]
for i in l:
    if i not in res:
        res.append(i)
print(res)

l=input("enter the list").split(",")
res=[]
for i in l:
    if i not in res and l.count(i)%2!=0:
        res.append(i)
print(res)

l=input("enter the list").split(",")
l.sort()
res=[]
i=0
for i in l:
    if i%2!=0:
        res.append(i)
    else:
         res.insert(0,i)
print(res)

n=int(input())
event=list(map(int,input().split()))
police=0
untreated=0
for x in event:
    if x==-1:
        if police>0:
            police-=1
        else:
            untreated+=1
    else:
        police+=x
print(untreated)

class Solution:
    def lemonadeChange(self, bills: List[int]) -> bool:
        five,ten=0,0
        for coin in bills:
            if coin==5:
                five+=1
            elif coin==10:
                if five>0:
                    five-=1
                    ten+=1
                else:
                    return False
            else:
                if five>0 and ten>0:
                    five-=1
                    ten-=1
                elif five>=3:
                    five-=3
                else:
                    return False
        return True