# -*- coding: utf-8 -*-
"""Training_day_6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaG8_iim2dIWhCQ-wHXrdAtyeL9TyaWH
"""

Recursion and Backtracking
--------------------------

> There are 4 different types of function arguments :

    1.default argument - use a predefined value inside function
     eg: def myFun(x,y=50):
            print("x:",x)
            print("y:",y)
         myFun(10)

    2.Keyword argument : pass values using parameter names
        eg:def student(fname,lname):
             print(fname,lname)
           student(fname="geeks",lname="joe")

    3.Positional arguments : arguments are assigned to the function based on position

    4.args and kwargs : if no.of arguments are unknown
        eg: def myFun(*args,**kwargs):
                print("non-keyword arguments(*args):")
                for args in args:
                    print(arg)
                print("keyword arguments (**kwargs):")
                for key, value in kwargs,items():
                    print(f"{key}=={value}")

                myFun('hey','welcome',first='geeks',mid='for',last='geeks')


RECURSION
---------

> starts from end and comes back.
> eg : for simple recursion:

        def fun(n):
            if n==0:
                return
            print(n)
            fun(n-1)

        n=10
        fun(n)

> first you should define a base case , whenever we are planning to write a recursion
  then logic

> find the min/max no.of steps shows us the recursion question

def fun(n):                     //tail recursion
    if n==0:
        return
    else:
        print(n,end=" ")
        fun(n-1)
n=5
fun(n)

def fun(n):                     //head recursion - happens when returning back
    if n==0:
        return
    else:
        fun(n-1)
        print(n,end=" ")
n=5
fun(n)

def fun(n):
    if n==0:
        return
    else:
        print(n,end=" ")
        fun(n-2)
n=10
fun(n)

def fun(n):
    if n==0:
        return
    else:
        fun(n-2)
        print(n,end=" ")
n=10
fun(n)

def fun(n):
    if n == 1:
        print(1, end=" ")
        return
    print(n, end=" ")
    fun(n - 1)
    print(n, end=" ")

fun(5)

def fun(n):
    if n==2:
        print(2,end=" ")
        return
    print(n,end=" ")
    fun(n-2)
    print(n,end=" ")
fun(10)

def fun(n):
    if n==0:
        return 200
    else:
        t=fun(n-1)
        print(n,end=" ")
        return t
n=5
print(fun(n))

def fun(n):                     //when n=1
    if n == 5:
        print(5, end=" ")
        return
    print(n, end=" ")
    fun(n+1)
    print(n, end=" ")

fun(1)

def fun(n,m=0):
    if n == m:
        return
    print(m+1, end=" ")
    fun(n,m+1)
    print(m+1, end=" ")

fun(5)

def fun(n):                     //geeks4geeks - Reduce a number to 1 by performing given operations
    if n==1:
        return 0
    elif n%2==0:
        return 1+fun(n//2)
    else:
        return 1+min(fun(n-1),fun(n+1))
n=15
print(fun(n))

Backtracking
------------

> Mainly implemented in 2D-Matrix
> matrix[i-1][j]=up  , matrix[i+1][j]=down  , matrix[i][j-1]=left  , matrix[i][j+1]=right

def wildfire(grid,i,j):
    if i<0 or i>=len(grid) or j<0 or j>=len(grid[0]) or grid[i][j]!=1:
        return
    grid[i][j]=2
    wildfire(grid,i+1,j) #down
    wildfire(grid,i+1,j) #up
    wildfire(grid,i,j-1) #right
    wildfire(grid,i,j+1) #left
matrix=[[1,1,1,1],
        [1,0,0,0],
        [0,0,1,1],
        [1,0,0,0]]
wildfire(matrix,0,0)
count=0
for i in range(len(matrix)):
    for j in range(len(matrix[0])):
        if matrix[i][j]==1:
            count+=1
print(count)

problem no:733

class Solution:
    def floodFill(self, image: List[List[int]], sr: int, sc: int, color: int) -> List[List[int]]:
        original = image[sr][sc]

        if original == color:
            return image

        def dfs(r, c):
            if r < 0 or r >= len(image) or c < 0 or c >= len(image[0]):
                return

            if image[r][c] != original:
                return

            image[r][c] = color

            dfs(r + 1, c)
            dfs(r - 1, c)
            dfs(r, c + 1)
            dfs(r, c - 1)

        dfs(sr, sc)
        return image

problem no:200

class Solution:
    def numIslands(self, grid: List[List[str]]) -> int:
        rows = len(grid)
        cols = len(grid[0])
        count = 0

        def dfs(r, c):
            if r < 0 or r >= rows or c < 0 or c >= cols:
                return

            if grid[r][c] == "0":
                return

            grid[r][c] = "0"

            dfs(r + 1, c)
            dfs(r - 1, c)
            dfs(r, c + 1)
            dfs(r, c - 1)

        for r in range(rows):
            for c in range(cols):
                if grid[r][c] == "1":
                    count += 1
                    dfs(r, c)

        return count

def maze(grid,path,i,j,n):              //robot moves only through down and right paths if its 1 it moves or dont move
    if i==n and j==n:
        print(path)
        return
    if i+1<=n and grid[i+1][j]==1:
        maze(grid, path+'D',i+1,j,n)
    if j+1<=n and grid[i][j+1]==1:
        maze(grid, path+'R',i,j+1,n)
grid=[[1,1,0,1],
      [1,1,0,1],
      [0,1,0,0],
      [1,1,1,1]]
n=len(grid)
maze(grid,"",0,0,n-1)