# -*- coding: utf-8 -*-
"""Training_day_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TCIGle29Q1izBdsOkI8h6RlYTlgO4h1g
"""

LINKED LIST
-----------
different types of LL:
1.Singly linked list - we can go only in one direction , either front or back
2.doubly linked list - we can go back'n'forth directions
3.circular linked list - we can go back from the end to start , ie : with a loop for singly LL

real life applications:
1.music player - spotify
2.Browser - go back and front in webpages
3.undo & redo button

class Node:                     #traversal of linked list without including the last data
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(10)
head.next = Node(20)
head.next.next = Node(30)
head.next.next.next = Node(40)
head.next.next.next.next = Node(50)

temp = head
while temp.next:
    print(temp.data, end=" ")
    temp = temp.next

class Node:                     #traversal of linked list by including the last data.used to add number at the end of the LL
    def __init__(self, data):
        self.data = data
        self.next = None

head = Node(10)
head.next = Node(20)
head.next.next = Node(30)
head.next.next.next = Node(40)
head.next.next.next.next = Node(50)

temp = head
while temp:
    print(temp.data, end=" ")
    temp = temp.next

problem no:876

class Solution:
    def middleNode(self, head: Optional[ListNode]) -> Optional[ListNode]:
        n = 0
        temp = head
        # Count nodes
        while temp:
            n += 1
            temp = temp.next
        # Move to middle
        mid = n // 2
        temp = head
        for _ in range(mid):
            temp = temp.next
        return temp

problem no:141


class Solution:
    def hasCycle(self, head: Optional[ListNode]) -> bool:
        fast=head
        slow=head
        while fast and fast.next:
            fast=fast.next.next
            slow=slow.next
            if fast==slow:
                return True
        return False

problem no:142

class Solution:
    def detectCycle(self, head: Optional[ListNode]) -> Optional[ListNode]:
        fast=head
        slow=head
        while fast and fast.next:
            fast=fast.next.next
            slow=slow.next
            if fast==slow:
                fast=head
                while fast!=slow:
                    fast=fast.next
                    slow=slow.next
                return slow
        return None

problem no:19

class Solution:
    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:
        dummy = ListNode(0)
        dummy.next = head

        fast = dummy
        slow = dummy

        # Move fast n+1 steps ahead
        for _ in range(n + 1):
            fast = fast.next

        # Move both pointers
        while fast:
            fast = fast.next
            slow = slow.next

        # Remove nth node from end
        slow.next = slow.next.next

        return dummy.next

problem no:21

class Solution:
    def mergeTwoLists(self, list1: Optional[ListNode], list2: Optional[ListNode]) -> Optional[ListNode]:
        dummy=ListNode()
        list3=dummy
        res=dummy
        while list1 and list2:
            if list1.val<list2.val:
                list3.next=list1
                list1=list1.next
                list3=list3.next
            else:
                list3.next=list2
                list2=list2.next
                list3=list3.next
        while list1:
            list3.next=list1
            list1=list1.next
            list3=list3.next
        while list2:
            list3.next=list2
            list2=list2.next
            list3=list3.next
        return res.next

problem no:206

class Solution:
    def reverseList(self, head: Optional[ListNode]) -> Optional[ListNode]:
        prev = None
        curr = head

        while curr:
            nxt = curr.next
            curr.next = prev
            prev = curr
            curr = nxt

        return prev